name: tensorflow_native
description: library for interact with tensor flow lite.
version: 0.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  ffi: ^2.0.1
